version: '3'

services:

### PHP-FPM + Caddy ##############################################
    app:
      container_name: ${COMPOSE_PROJECT_NAME}_app_base
      build:
        args:
          - NOVA_USERNAME=${NOVA_USERNAME}
          - NOVA_PASSWORD=${NOVA_PASSWORD}
          - PHP_VERSION=${PHP_VERSION}
        context: .
        dockerfile: docker/app/Dockerfile_base_image
      image: registry.gitlab.com/${REPOSITORY_NAME:-flagstudio}/${COMPOSE_PROJECT_NAME}:base # образ, который строим. НЕ ТОТ из которого строимся
      ports:
        - "8080:8080"
