- name: Create and set perimissions for data dir
  file:
    path: "{{project_remote_path}}{{data_path_host}}"
    recurse: yes
    state: directory
    mode: "0777"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
  become: yes
