#- name: Create User
#  command: ssh-copy-id -i ansible_ssh_private_key_file -o StrictHostKeyChecking=no ansible_user@ansible_host

- name: Set authorized key took from file
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', ansible_ssh_public_key_file) }}"
