- name: Create traefik directory
  file:
    path: "{{project_remote_path}}{{traefik_directory_name}}"
    recurse: yes
    state: directory
    mode: "0775"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
  become: yes

- name: Upload traefik docker-compose.yml file
  copy:
    src: docker-compose.yml
    dest: "{{project_remote_path}}{{traefik_directory_name}}docker-compose.yml"
    mode: "0775"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"

- name: Create .env file
  file:
    path: "{{project_remote_path}}{{traefik_directory_name}}.env"
    state: touch
    mode: "0775"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
  become: yes

- name: Fill variables to the .env file
  lineinfile:
    path: "{{project_remote_path}}{{traefik_directory_name}}.env"
    line: "{{item}}"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
  with_items:
    - EMAIL={{admin_email}}
    - TRAEFIK_DOMAIN={{traefik_uri}}

- name: Create traefik data directory
  file:
    path: "{{project_remote_path}}{{traefik_directory_name}}data"
    recurse: yes
    state: directory
    mode: "0777"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
  become: yes

- name: Create usersfile
  file:
    path: "{{project_remote_path}}{{traefik_directory_name}}data/.usersfile"
    state: touch
    mode: "0777"
    owner: "{{ansible_user}}"
    group: "{{ansible_user}}"
  become: yes

- name: Create basic auth login
  shell: htpasswd -nb {{basic_auth_login}} {{basic_auth_password}} > {{project_remote_path}}{{traefik_directory_name}}data/.usersfile

- name: Check for traefik network exists
  command:
    cmd: docker network inspect {{traefik_network}}
  ignore_errors: yes
  register: traefik_network_exist_status

- name: Create traefik network
  command:
    cmd: docker network create {{traefik_network}}
  when: traefik_network_exist_status.failed

- name: Build & up traefik
  shell: docker-compose up -d
  args:
    chdir: "{{project_remote_path}}{{traefik_directory_name}}"

- name: Wait for traefik up
  wait_for:
    timeout: 5
